# Generated by Django 4.1.7 on 2023-10-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('age', models.IntegerField(default=0)),
                ('photo', models.ImageField(upload_to='directors/')),
            ],
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='Bio',
            new_name='bio',
        ),
    ]
