# Generated by Django 4.1.7 on 2023-10-15 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_movie_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
    ]
